//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class tbl_cat_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cat_producto()
        {
            this.tbl_productos = new HashSet<tbl_productos>();
        }

        public int id_cat_producto { get; set; }
        [Display(Name = "Categoría de producto")]
        [Required(ErrorMessage = "Digite un nombre para la categoría")]
        [StringLength(50, ErrorMessage = "El límite de caracteres es de 50")]
        public string nombre { get; set; }
        [Display(Name = "Descripción de categoría")]
        [Required(ErrorMessage = "Digite una descripción para la categoría")]
        [StringLength(100, ErrorMessage = "El límite de caracteres es de 100")]
        public string descripcion { get; set; }
        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_productos> tbl_productos { get; set; }
    }
}
