//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rol_usuario
    {
        public int id_rol_usuario { get; set; }
        public int id_usuario { get; set; }
        public int id_rol { get; set; }
    
        public virtual tbl_rol tbl_rol { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
