//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_moneda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_moneda()
        {
            this.tbl_arqueocaja_det = new HashSet<tbl_arqueocaja_det>();
            this.tbl_denominacion = new HashSet<tbl_denominacion>();
            this.tbl_tasacambio = new HashSet<tbl_tasacambio>();
            this.tbl_tasacambio1 = new HashSet<tbl_tasacambio>();
        }

        public int id_moneda { get; set; }

        [Display(Name = "Nombre: ")]
        [Required(ErrorMessage = "Escriba el nombre de la moneda.")]
        [StringLength(50, ErrorMessage = "La cantidad máxima de caracteres permitidos es de 50")]
        public string nombre { get; set; }

        [Display(Name = "Signo: ")]
        [Required(ErrorMessage = "Escriba el signo.")]
        [StringLength(10, ErrorMessage = "La cantidad máxima de caracteres permitidos es de 10")]
        public string signo { get; set; }
        public int estado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_arqueocaja_det> tbl_arqueocaja_det { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_denominacion> tbl_denominacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tasacambio> tbl_tasacambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tasacambio> tbl_tasacambio1 { get; set; }
    }
}
