//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_cat_gastos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cat_gastos()
        {
            this.tbl_gastos = new HashSet<tbl_gastos>();
        }
    
        public int id_cat_gasto { get; set; }

        [Display(Name = "Categoría")]
        [Required(ErrorMessage ="Campo obligatorio")]
        [StringLength(50, ErrorMessage ="Ha excedido el valor máximo de caracteres")]
        public string nombre_cat { get; set; }

        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(100, ErrorMessage = "Ha excedido el valor máximo de caracteres")]
        public string desc_cat { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_gastos> tbl_gastos { get; set; }
    }
}
