//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_gastos
    {
        public int id_gasto { get; set; }

        [Display(Name = "Kermesse")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int id_kermesse { get; set; }

        [Display(Name = "Categoría")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public int id_cat_gasto { get; set; }

        [Display(Name = "Fecha gasto")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public System.DateTime fecha_gasto { get; set; }

        [Display(Name = "Concepto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        [StringLength(200, ErrorMessage = "Ha excedido el valor máximo de caracteres")]
        public string concepto { get; set; }

        [Display(Name = "Monto")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public decimal monto { get; set; }
        public int estado { get; set; }
        public int usuario_creacion { get; set; }
        public Nullable<int> usuario_modificacion { get; set; }
        public Nullable<int> usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual tbl_cat_gastos tbl_cat_gastos { get; set; }
        public virtual tbl_kermesse tbl_kermesse { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
        public virtual tbl_usuario tbl_usuario1 { get; set; }
        public virtual tbl_usuario tbl_usuario2 { get; set; }
    }
}
