//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_tasacambio_det
    {
        public int id_tasacambio_det { get; set; }
        public int id_tasacambio { get; set; }
        [Display(Name = "Fecha")]
        [Required(ErrorMessage = "Ingrese una fecha")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime fecha { get; set; }
        [Display(Name = "Cambio")]
        [Required(ErrorMessage = "Ingrese un cambio")]
        public decimal tipo_cambio { get; set; }
        public int estado { get; set; }

        public virtual tbl_tasacambio tbl_tasacambio { get; set; }
    }
}
