//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_arqueocaja_det
    {
        public int id_arqueocaja_det { get; set; }

        [Display(Name = "Arqueo Caja: ")]
        public int id_arqueocaja { get; set; }

        [Display(Name = "Moneda: ")]
        public int id_moneda { get; set; }

        [Display(Name = "Denominación: ")]
        public int id_denominacion { get; set; }

        [Display(Name = "Cantidad: ")]
        [Required(ErrorMessage = "Escriba la cantidad.")]
        public decimal cantidad { get; set; }

        [Display(Name = "Subtotal: ")]
        [Required(ErrorMessage = "Escriba el subtotal.")]
        public decimal subtotal { get; set; }

        public virtual tbl_arqueocaja tbl_arqueocaja { get; set; }
        public virtual tbl_denominacion tbl_denominacion { get; set; }
        public virtual tbl_moneda tbl_moneda { get; set; }
    }
}