//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_productos
    {
        public int id_producto { get; set; }
        public string producto { get; set; }
        public int id_comunidad { get; set; }
        public string comunidad { get; set; }
        public int id_cat_producto { get; set; }
        public string cat_producto { get; set; }
        public string desc_presentacion { get; set; }
        public int cantidad { get; set; }
        public decimal precio_venta { get; set; }
        public int estado { get; set; }
    }
}
