//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Gastos
    {
        public int id_gasto { get; set; }
        public string kermesse { get; set; }
        public string categoria { get; set; }
        public System.DateTime fecha_gasto { get; set; }
        public string concepto { get; set; }
        public decimal monto { get; set; }
        public int estado { get; set; }
    }
}
