//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KermesseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_listaprecio
    {
        public int id_listaprecio { get; set; }
        public string lista_precio { get; set; }
        public int id_kermesse { get; set; }
        public string kermesse { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
    }
}
